### ISSUE TITLE
Plugin fails to load in Protege

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-plugin#1]
This  [line](https://github.com/protegeproject/lucene-search-plugin/blob/nci-lucene-search/pom.xml#L176) in the `pom.xml` file causes a class cast exception when loading the plugin in Protege. Narrowing the exports to not include `OWLEditorKit` seems to fix it.

**Comment by matthewhorridge** [comment]
I'm just wondering why any exports are declared at all here.  Packages should only be exported if they are going to be made available to another plugin - i.e. in this case plugins to the Lucene plugin.

In general (and in  my understanding) packages from the protege distribution that are exported by plugins may cause problems and it's probably an error to do this.  In this case, all of the classes from the `org.protege.editor` package and sub packages will be exported by the Lucene plugin.  These classes will be different (because they are loaded from a different class loader) to the classes in this package exported by the protege distribution - hence the class cast exception.

**Comment by bdionne** [comment]
This makes sense, and explains the class cast exception we see with `OWLEditorKit`. I tried removing the exports in the lucene plugin and it fails with a class not found error, if I recall it was `OWLWorkSpaceTab`

**Comment by matthewhorridge** [comment]
@bdionne I don't have the dependencies for this plugin to hand.  Any chance you could post a copy of the manifest that get generated by the build? (The one where it fails)

**Comment by bdionne** [comment]
[plugin manifest](https://gist.github.com/bdionne/9f465a571ff83883c874b4c9f67f629d)

**Comment by matthewhorridge** [comment]
Thanks.  The exports look o.k. to me (at least for org.protege.editor.owl.ui, which is the package containing OWLWorkspaceTab), but the exports look messed up.  I'll check the exports for this and the lucene dependencies

**Comment by rsgoncalves** [comment]
Matthew, by removing all the exports we arrive at the issue that I emailed you about some time back (as Bob said, a `ClassNotFound` error for `OWLWorkSpaceTab`). Adding the export directive(s) fixes that.

**Comment by matthewhorridge** [comment]
o.k. I don't think this is the right solution though.  The lucene plugin shouldn't export anything as it's not a bundle that provides functionality for other bundles.  

As a workaround, you could try WorkspaceTab instead of OWLWorkspaceTab

**Comment by rsgoncalves** [comment]
I am using WorkspaceTab:

```
<extension id="LuceneQueryTab"
               point="org.protege.editor.core.application.WorkspaceTab">
        <label value="Lucene Query"/>
        <class value="org.protege.editor.owl.ui.OWLWorkspaceViewsTab"/>
...
</extension>
```

Could it be then that some packages are not exported by Protege, thus resulting in the WorkspaceTab class not found?
